#!/bin/bash
# =============================================================================
# Setup Local Environment
# =============================================================================
# Populates .env.local from 1Password vault (Engineering-Staging/sauce-web)
# Requires: 1Password CLI (op) - https://1password.com/downloads/command-line/
# =============================================================================

set -e

VAULT="Engineering-Staging"
ITEM="sauce-web"
ENV_FILE=".env.local"

echo "Setting up local environment from 1Password..."
echo "Vault: $VAULT"
echo "Item: $ITEM"
echo ""

# Check if op CLI is installed
if ! command -v op &> /dev/null; then
    echo "Error: 1Password CLI (op) is not installed."
    echo "Install it with: brew install 1password-cli"
    echo "Then sign in with: op signin"
    exit 1
fi

# Check if signed in
if ! op account get &> /dev/null; then
    echo "Error: Not signed in to 1Password CLI."
    echo "Sign in with: op signin"
    exit 1
fi

echo "Fetching secrets from 1Password..."

SUPABASE_URL=$(op read "op://$VAULT/$ITEM/project_url")
SUPABASE_ANON_KEY=$(op read "op://$VAULT/$ITEM/api_key")

if [ -z "$SUPABASE_URL" ] || [ -z "$SUPABASE_ANON_KEY" ]; then
    echo "Error: Failed to fetch secrets from 1Password."
    exit 1
fi

# Create .env.local
cat > "$ENV_FILE" << EOF
# Generated by scripts/setup-local-env.sh
# Source: 1Password vault "$VAULT/$ITEM"

NEXT_PUBLIC_SUPABASE_URL=$SUPABASE_URL
NEXT_PUBLIC_SUPABASE_ANON_KEY=$SUPABASE_ANON_KEY
NEXT_PUBLIC_APP_URL=http://localhost:3000
NEXT_PUBLIC_APP_ENV=development
EOF

echo "Created $ENV_FILE successfully!"
echo ""
echo "You can now run: npm run dev"
